In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("./Resources/220614COVID19MEXICO.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16192035 entries, 0 to 16192034
Data columns (total 40 columns):
 #   Column                 Dtype
---  ------                 -----
 0   FECHA_ACTUALIZACION    object
 1   ID_REGISTRO            object
 2   ORIGEN                 int64
 3   SECTOR                 int64
 4   ENTIDAD_UM             int64
 5   SEXO                   int64
 6   ENTIDAD_NAC            int64
 7   ENTIDAD_RES            int64
 8   MUNICIPIO_RES          int64
 9   TIPO_PACIENTE          int64
 10  FECHA_INGRESO          object
 11  FECHA_SINTOMAS         object
 12  FECHA_DEF              object
 13  INTUBADO               int64
 14  NEUMONIA               int64
 15  EDAD                   int64
 16  NACIONALIDAD           int64
 17  EMBARAZO               int64
 18  HABLA_LENGUA_INDIG     int64
 19  INDIGENA               int64
 20  DIABETES               int64
 21  EPOC                   int64
 22  ASMA                   int64
 23  INMUSUPR               int64
 24  HIPERTENSION           int64
 25  OTRA_COM               int64
 26  CARDIOVASCULAR         int64
 27  OBESIDAD               int64
 28  RENAL_CRONICA          int64
 29  TABAQUISMO             int64
 30  OTRO_CASO              int64
 31  TOMA_MUESTRA_LAB       int64
 32  RESULTADO_LAB          int64
 33  TOMA_MUESTRA_ANTIGENO  int64
 34  RESULTADO_ANTIGENO     int64
 35  CLASIFICACION_FINAL    int64
 36  MIGRANTE               int64
 37  PAIS_NACIONALIDAD      object
 38  PAIS_ORIGEN            object
 39  UCI                    int64
dtypes: int64(33), object(7)
memory usage: 4.8+ GB

In [45]:
cols=[]
for x in df.columns:
    cols.append(x)

In [46]:
cols

['FECHA_ACTUALIZACION',
 'ID_REGISTRO',
 'ORIGEN',
 'SECTOR',
 'ENTIDAD_UM',
 'SEXO',
 'ENTIDAD_NAC',
 'ENTIDAD_RES',
 'MUNICIPIO_RES',
 'TIPO_PACIENTE',
 'FECHA_INGRESO',
 'FECHA_SINTOMAS',
 'FECHA_DEF',
 'INTUBADO',
 'NEUMONIA',
 'EDAD',
 'NACIONALIDAD',
 'EMBARAZO',
 'HABLA_LENGUA_INDIG',
 'INDIGENA',
 'DIABETES',
 'EPOC',
 'ASMA',
 'INMUSUPR',
 'HIPERTENSION',
 'OTRA_COM',
 'CARDIOVASCULAR',
 'OBESIDAD',
 'RENAL_CRONICA',
 'TABAQUISMO',
 'OTRO_CASO',
 'TOMA_MUESTRA_LAB',
 'RESULTADO_LAB',
 'TOMA_MUESTRA_ANTIGENO',
 'RESULTADO_ANTIGENO',
 'CLASIFICACION_FINAL',
 'MIGRANTE',
 'PAIS_NACIONALIDAD',
 'PAIS_ORIGEN',
 'UCI']

In [57]:
new_cols = ['DATE UPDATE',
 'REGISTRATION_ID',
 'SOURCE',
 'SECTOR',
 'ENTITY_UM',
 'SEX',
 'ENTITY_NAC',
 'ENTITY_RES',
 'MUNICIPALITY_RES',
 'TYPE_PATIENT',
 'ADMISSION DATE',
 'DATE_SYMPTOMS',
 'DATE_DEF',
 'INTUBATED',
 'PNEUMONIA',
 'AGE',
 'NATIONALITY',
 'PREGNANCY',
 'SPEAK_LANGUAGE_INDIG',
 'INDIGENOUS',
 'DIABETES',
 'COPD',
 'ASTHMA',
 'INMUSUPR',
 'HYPERTENSION',
 'OTHER_COM',
 'CARDIOVASCULAR',
 'OBESITY',
 'RENAL_CHRONIC',
 'SMOKING',
 'ANOTHER CASE',
 'TAKE_LAB_SAMPLE',
 'LAB_RESULT',
 'TAKE_SAMPLE_ANTIGEN',
 'RESULT_ANTIGEN',
 'FINAL_CLASSIFICATION',
 'MIGRANT',
 'COUNTRY_NATIONALITY',
 'COUNTRY OF ORIGIN',
 'ICU']

In [58]:
df.columns = new_cols
df.head()

,DATE UPDATE,REGISTRATION_ID,SOURCE,SECTOR,ENTITY_UM,SEX,ENTITY_NAC,ENTITY_RES,MUNICIPALITY_RES,TYPE_PATIENT,...,ANOTHER CASE,TAKE_LAB_SAMPLE,LAB_RESULT,TAKE_SAMPLE_ANTIGEN,RESULT_ANTIGEN,FINAL_CLASSIFICATION,MIGRANT,COUNTRY_NATIONALITY,COUNTRY OF ORIGIN,ICU
0,2022-06-14,z24953,1,12,9,1,9,9,10,1,...,1,1,2,2,97,7,99,México,97,97
1,2022-06-14,z23d9d,1,12,22,2,24,22,9,1,...,2,2,97,2,97,6,99,México,97,97
2,2022-06-14,z49a69,1,12,23,1,23,23,4,2,...,1,2,97,2,97,2,99,México,97,1
3,2022-06-14,z482b8,2,12,9,2,9,9,12,1,...,2,2,97,2,97,1,99,México,97,97
4,2022-06-14,z3bf80,2,12,8,2,8,8,37,1,...,2,1,1,2,97,3,99,México,97,97